config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :actividads
  resources :noticia
  resources :noticia
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admins
  #get '/eventos'=>'eventos#index'
  #get '/posts' =>'posts/index'
  #get '/posts/new'=>'posts#new'
  #get '/eventos/new'=>'eventos#new'
  
  root 'main#index'
  
  resources :posts
  resources :eventos
  
  #get 'main/index'

  #get 'evento/formulario_evento'
  #get '/eventos/eventos_publicados'
  #get 'eventos/new'
  
  #match ':controller(/:action(/:id))', :via => :get
  #match ':controller(/:action)', :via => :get

end

app/models/actividad.rb
class Actividad < ActiveRecord::Base
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    :url => "/ckeditor_assets/attachments/:id/:filename",
                    :path => ":rails_root/public/ckeditor_assets/attachments/:id/:filename"

  validates_attachment_presence :data
  validates_attachment_size :data, :less_than => 100.megabytes
  do_not_validate_attachment_file_type :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    :url  => "/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :path => ":rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :styles => { :content => '800>', :thumb => '118x100#' }

  validates_attachment_presence :data
  validates_attachment_size :data, :less_than => 2.megabytes
  validates_attachment_content_type :data, :content_type => /\Aimage/

  def url_content
    url(:content)
  end
end

app/models/noticium.rb
class Noticium < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/actividads_controller.rb
class ActividadsController < ApplicationController
  before_action :set_actividad, only: [:show, :edit, :update, :destroy]

  # GET /actividads
  # GET /actividads.json
  def index
    @actividads = Actividad.all
  end

  # GET /actividads/1
  # GET /actividads/1.json
  def show
  end

  # GET /actividads/new
  def new
    @actividad = Actividad.new
  end

  # GET /actividads/1/edit
  def edit
  end

  # POST /actividads
  # POST /actividads.json
  def create
    @actividad = Actividad.new(actividad_params)

    respond_to do |format|
      if @actividad.save
        format.html { redirect_to @actividad, notice: 'Actividad was successfully created.' }
        format.json { render :show, status: :created, location: @actividad }
      else
        format.html { render :new }
        format.json { render json: @actividad.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /actividads/1
  # PATCH/PUT /actividads/1.json
  def update
    respond_to do |format|
      if @actividad.update(actividad_params)
        format.html { redirect_to @actividad, notice: 'Actividad was successfully updated.' }
        format.json { render :show, status: :ok, location: @actividad }
      else
        format.html { render :edit }
        format.json { render json: @actividad.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /actividads/1
  # DELETE /actividads/1.json
  def destroy
    @actividad.destroy
    respond_to do |format|
      format.html { redirect_to actividads_url, notice: 'Actividad was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_actividad
      @actividad = Actividad.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def actividad_params
      params.require(:actividad).permit(:title, :body, :fecha)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.order("created_at DESC")
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to articles_path, notice: "The article has been successfully created."
    else
      render action: "new"
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update_attributes(article_params)
      redirect_to articles_path, notice: "The article has been successfully updated."
    else
      render action: "edit"
    end
  end

private

  def article_params
    params.require(:article).permit(:title, :body)
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
  
  def mailchimpi
  end  
  
end

app/controllers/noticia_controller.rb
class NoticiaController < ApplicationController
  before_action :set_noticium, only: [:show, :edit, :update, :destroy]

  # GET /noticia
  # GET /noticia.json
  def index
    @noticia = Noticium.all
  end

  # GET /noticia/1
  # GET /noticia/1.json
  def show
  end

  # GET /noticia/new
  def new
    @noticium = Noticium.new
  end

  # GET /noticia/1/edit
  def edit
  end

  # POST /noticia
  # POST /noticia.json
  def create
    @noticium = Noticium.new(noticium_params)

    respond_to do |format|
      if @noticium.save
        format.html { redirect_to @noticium, notice: 'a noticia fue creada con éxito.' }
        format.json { render :show, status: :created, location: @noticium }
      else
        format.html { render :new }
        format.json { render json: @noticium.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /noticia/1
  # PATCH/PUT /noticia/1.json
  def update
    respond_to do |format|
      if @noticium.update(noticium_params)
        format.html { redirect_to @noticium, notice: 'La noticia fue actualizada.' }
        format.json { render :show, status: :ok, location: @noticium }
      else
        format.html { render :edit }
        format.json { render json: @noticium.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /noticia/1
  # DELETE /noticia/1.json
  def destroy
    @noticium.destroy
    respond_to do |format|
      format.html { redirect_to noticia_url, notice: 'La noticia fue eliminada' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_noticium
      @noticium = Noticium.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def noticium_params
      params.require(:noticium).permit(:title, :body)
    end
end

app/controllers/seguidores_controller.rb
class SeguidoresController < ApplicationController
    def index
        require 'smarter_csv'
        options = {}
        SmarterCSV.process('input_file.csv', options) do |chunk|
            chunk.each do |data_hash|
            Moulding.create!( data_hash )
            end
        end
    end
end

app/helpers/actividads_helper.rb
module ActividadsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/busqueda_helper.rb
module BusquedaHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/noticia_helper.rb
module NoticiaHelper
end

app/views/actividads/_form.html.erb
<%= form_for(@actividad) do |f| %>
  <% if @actividad.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@actividad.errors.count, "error") %> prohibited this actividad from being saved:</h2>

      <ul>
      <% @actividad.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.cktext_area :body %>
  </div>
  <div class="field">
    <%= f.label :fecha %><br>
    <%= f.date_select :fecha %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/actividads/edit.html.erb
<h1>Editar Evento</h1>

<%= render 'form' %>

<%= link_to 'Show', @actividad %> |
<%= link_to 'Back', actividads_path %>

app/views/actividads/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Eventos</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Fecha</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @actividads.each do |actividad| %>
      <tr>
        <td><%= actividad.title %></td>
        <td><%= raw actividad.body %></td>
        <td><%= actividad.fecha %></td>
        <td><%= link_to 'Show', actividad %></td>
        <td><%= link_to 'Edit', edit_actividad_path(actividad) %></td>
        <td><%= link_to 'Destroy', actividad, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Evento', new_actividad_path %>

app/views/actividads/new.html.erb
<h1>Nueva Actividad</h1>

<%= render 'form' %>

<%= link_to 'Back', actividads_path %>

app/views/actividads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @actividad.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= raw @actividad.body %>
</p>

<p>
  <strong>Fecha:</strong>
  <%= @actividad.fecha %>
</p>

<%= link_to 'Edit', edit_actividad_path(@actividad) %> |
<%= link_to 'Back', actividads_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/main/index.html.erb
<div id= "header">
    <img src="/imagenes/logo_grande.jpg" alt="logo"/>
    <h1>Sistema de Gestión de Contenido</h1>
</div>
<div id="menu">
<p><body vlink= white link=white>
    <%= link_to("Publicar evento", 
        {:controller => 'actividads',
         :action => 'new'}) %>
    &nbsp;         
    <%= link_to("Publicar noticia", 
        {:controller => 'noticia',
         :action => 'new'}) %>
    &nbsp;
    <%= link_to("Eventos", 
        {:controller => 'actividads',
         :action => 'index'}) %>
    &nbsp;
    <%= link_to("Noticias", 
        {:controller => 'noticia',
         :action => 'index'}) %>
    &nbsp;
    <!-- link_to ("get csv",
        {:controller => 'seguidores',
         :action => 'index'}) %>
    -->
    
    &nbsp;
    <%= link_to "Gestor de listas", "https://login.mailchimp.com/?_ga=1.87043356.524061047.1463891449", :target => "_blank" %>


    <form>
        <input type="text" placeholder="Buscar..." required>
        <input type="button" value="Buscar">
    </form>
</body></p>
</div>
<div>
            <a class="muut" href="https://muut.com/i/musicamigos">musicamigos</a>
        <script src="//cdn.muut.com/1/moot.es.min.js"></script>
      
</div>


<div>
<footer>
   <!-- Begin MailChimp Signup Form -->
<link href="//cdn-images.mailchimp.com/embedcode/slim-10_7.css" rel="stylesheet" type="text/css">
<style type="text/css">
	#mc_embed_signup{background:#1551A0; clear:left; font:14px Helvetica,Arial,sans-serif;  width:300px;}
	/* Add your own MailChimp form style overrides in your site stylesheet or in this style block.
	   We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
</style>
<div id="mc_embed_signup">
<form action="//facebook.us13.list-manage.com/subscribe/post?u=0fc6ee55f3ee648f471efc32b&amp;id=81b4c62aeb" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
    <div id="mc_embed_signup_scroll">
	<label for="mce-EMAIL">Suscríbase a nuestra lista de correos</label>
	<input type="email" value="" name="EMAIL" class="email" id="mce-EMAIL" placeholder="email address" required>
    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
    <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_0fc6ee55f3ee648f471efc32b_81b4c62aeb" tabindex="-1" value=""></div>
    <div class="clear"><input type="submit" value="Suscribirse" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
    </div>
</form>
</div>

<!--End mc_embed_signup-->
</footer>
</div>
<style>
    body{
      font-family: tahoma;
      color: #ffffff;
    }
    #header {
        background-color:white;
        color: #1551A0;
        text-align:center;
        padding:10px;
    }
    
    #menu {
        background-color: #1551A0;
        color: white;
        text-align: center;
        padding:10px;
    }
    footer{
        background-color: #1551A0;
        color: white;
        text-align: center;
        padding:10px;
    }
</style>

app/views/noticia/_form.html.erb
<%= form_for(@noticium) do |f| %>
  <% if @noticium.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@noticium.errors.count, "error") %> prohibited this noticium from being saved:</h2>

      <ul>
      <% @noticium.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.cktext_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/noticia/edit.html.erb
<h1>Editar Noticia</h1>

<%= render 'form' %>

<%= link_to 'Show', @noticium %> |
<%= link_to 'Back', noticia_path %>

app/views/noticia/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Noticias</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @noticia.each do |noticium| %>
      <tr>
        <p><td><%= noticium.title %></td></p>
        <p><td><%= raw noticium.body %></td></p>
        <p><td><%= link_to 'Show', noticium %></td>
        <td><%= link_to 'Edit', edit_noticium_path(noticium) %></td>
        <td><%= link_to 'Destroy', noticium, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </p>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nueva Noticia', new_noticium_path %>

app/views/noticia/new.html.erb
<h1>Nueva noticia</h1>

<%= render 'form' %>

<%= link_to 'Back', noticia_path %>

app/views/noticia/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <%= @noticium.title %>
</p>

<p>
  <%= raw @noticium.body %>
</p>

<%= link_to 'Edit', edit_noticium_path(@noticium) %> |
<%= link_to 'Back', noticia_path %>